KinoApp/Controllers/BetController.cs
using Kino.Models.KinoDBModel;
using KinoApp.Helpers;
using KinoApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using KinoApp.ServiceHelpers;
using KinoApp.ServiceHelpers.Bets;
using Newtonsoft.Json;
using System.Reflection;

namespace KinoApp.Controllers
{
    public class BetController : Controller
    {
        private readonly IHttpContextAccessor httpContext;
        private readonly IServiceMethods serviceMethods;

        public BetController(IHttpContextAccessor httpContext, IServiceMethods serviceMethods)
        {
            this.httpContext = httpContext;
            this.serviceMethods = serviceMethods;
        }

        [Authorize]
        [HttpGet]
        public IActionResult NewBet()
        {
            NewBetViewModel newBetViewModel = null;

            if(TempData["Errors"] != null)
            {
                ViewBag.Errors = TempData["Errors"];
            }

            if(TempData["Error"] != null)
            {
                ViewBag.Error = TempData["Error"];
            }

            if(TempData["Success"] != null)
            {
                ViewBag.Success = TempData["Success"];
            }

            if(TempData["ModelAsJson"] != null)
            {
                var ViewModelAsJson = TempData["ModelAsJson"] as string;
                newBetViewModel = JsonConvert.DeserializeObject<NewBetViewModel>(ViewModelAsJson);
                if (GeneralHelper.IsObjectEmpty(newBetViewModel))
                {
                    newBetViewModel = null;
                }
            }

            return View("NewBetScreen", newBetViewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult NewBet(NewBetViewModel newBetViewModel)
        {
            var result = ValidateNewBet(newBetViewModel);
            if (!result.Success)
            {
                TempData["Errors"] = result.Data;
                TempData["ModelAsJson"] = JsonConvert.SerializeObject(newBetViewModel);
            }
            else
            {
                var newBet = new Bet
                {
                    BetAmount = newBetViewModel.BetAmount,
                    BetDate = DateTime.Now,
                    NoOfNumbers = newBetViewModel.NumberOfSelectedNumbers,
                    SelectedNumbers = newBetViewModel.SelectedNumbers,
                    Outcome = 1,
                    UserId = ((ClaimsIdentity)httpContext.HttpContext.User.Identity).GetUserId()
                };

                serviceMethods.PerformPost(BetServiceEndpoints.AddBet, new[] { newBetViewModel.NumberOfDraws.HasValue ? newBetViewModel.NumberOfDraws.Value.ToString() : "" }, newBet, out var res);
                if (!res.Success)
                {
                    TempData["Error"] = res.Message;
                    TempData["ModelAsJson"] = JsonConvert.SerializeObject(newBetViewModel);
                }
                else
                {
                    TempData["Success"] = "Bet submitted successfully!";
                    return Redirect("~/Bet/NewBet");
                }

            }
            return Redirect("~/Bet/NewBet");
        }


        #region Helper Methods

        private OperationResult ValidateNewBet(NewBetViewModel newBetViewModel)
        {
            var errors = new List<string>();

            if (!newBetViewModel.NumberOfSelectedNumbers.HasValue)
            {
                errors.Add("Please select the number of numbers for the bet.");
            }
            else if(newBetViewModel.NumberOfSelectedNumbers.Value < 1 || newBetViewModel.NumberOfSelectedNumbers.Value > 12)
            {
                errors.Add("The number of selected number must be between 1 and 12.");
            }

            if(!newBetViewModel.NumberOfDraws.HasValue)
            {
                errors.Add("Please select the number of draws.");
            }
            else if (newBetViewModel.NumberOfDraws.Value < 1 || newBetViewModel.NumberOfDraws.Value > 3)
            {
                errors.Add("The number of draws must be between 1 and 3.");
            }

            if (!newBetViewModel.BetAmount.HasValue)
            {
                errors.Add("Please select a bet amount.");
            }

            //TODO: Add decimal validation in allowed values

            if (string.IsNullOrEmpty(newBetViewModel.SelectedNumbers))
            {
                errors.Add("No numbers have been selected.");
            }
            else
            {
                var selectedNumbers = newBetViewModel.SelectedNumbers.Split("#");
                var numbersOk = true;
                foreach(var number in selectedNumbers)
                {
                    var success = int.TryParse(number, out var n);
                    if (!success)
                    {
                        errors.Add("Invalid character submited as a number.");
                        numbersOk = false;
                        break;
                    }
                    else if(n < 1 || n > 80)
                    {
                        errors.Add("Selected numbers must be between 1 and 80.");
                        numbersOk = false;
                        break;
                    }
                }

                if (numbersOk)
                {
                    if(newBetViewModel.NumberOfSelectedNumbers.HasValue && newBetViewModel.NumberOfSelectedNumbers.Value > selectedNumbers.Length)
                    {
                        errors.Add(string.Format("You have selected less numbers ({0}) than you declared ({1}).", selectedNumbers.Length, newBetViewModel.NumberOfSelectedNumbers.Value));
                    }

                    if (newBetViewModel.NumberOfSelectedNumbers.HasValue && newBetViewModel.NumberOfSelectedNumbers.Value < selectedNumbers.Length)
                    {
                        errors.Add(string.Format("You have selected more numbers ({0}) than you declared ({1}).", selectedNumbers.Length, newBetViewModel.NumberOfSelectedNumbers.Value));
                    }
                }
            }

            return new OperationResult 
            {
                Success = errors.Count() == 0,
                Data = errors
            };
        }



        #endregion

    }
}

KinoApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using KinoApp.Helpers; 
@{ var currentUser = ((ClaimsIdentity)User.Identity).GetCurrentUser(); }
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KinoApp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item">
                <img class="img-logo-top" src="~/Images/kino-logo.png" title="Home" onclick="redirectToHome();"/>
                @*<a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>*@
            </div>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link btn btn-gray" asp-controller="Bet" asp-action="NewBet">Play now!</a>
                    </li>
                </ul>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="nav-item dropdown navbar-items-distance">
                    <a style="color:yellow !important" class='nav-link dropdown-toggle login-link' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                        <i class='fas fa-user' ></i>@currentUser.Username
                    </a>
                    <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
                        <a class="nav-link" style="color:yellow !important" asp-controller="" asp-action=""><i class="fas fa-history"></i>Past draws</a>
                        <a class="nav-link" style="color:yellow !important" asp-controller="Account" asp-action="Logout"><i class="fas fa-sign-out-alt"></i>Logout</a>
                    </div>
                        
                </div>
            }
            else
            {
                <div class="nav-item">
                    <a style="color:yellow !important" class="nav-link" asp-controller="Account" asp-action="Login"><i class="fas fa-sign-in-alt"></i>Login</a>
                </div>
            }

        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <div style="text-align:left;width:50%;float:left">
                &copy; 2021 - Kino by Tony
            </div>
            <div style="text-align: right; width: 50%;float:left ">
                <i class="fas fa-thumbs-up"></i>Play Responsibly
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>